name: Pages upload

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Create directory
        run: mkdir dist

      # https://github.com/dulvui/godot-4-html-export
      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1
        with:
          godot-version: 4.3
          godot-channel: stable

      # https://github.com/rossjrw/pr-preview-action
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist/
          action: auto
          token: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/dulvui/itchio-butler-upload
      - name: Upload to itch.io
        if: ${{ github.event.pull_request.merged == true }}
        uses: dulvui/itchio-butler-upload@v0.0.1
        with:
          working-directory: ./dist
          api-key: ${{ secrets.ITCHIO_API_KEY }}
          user: lee5i3
          game: flappyfairy
          channel: html5