name: Deploy PR previews

permissions:
  contents: read
  pages: write
  id-token: write

concurrency: preview-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL

      # Upload Artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build/WebGL/WebGL

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: Build
          path: .

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .